services:

  # ============================================
  # FRONTEND SERVICE (Vue.js)
  # ============================================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: papairs-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_AUTH_SERVICE_URL=http://localhost:8081
      - VITE_DOCS_SERVICE_URL=http://localhost:8082
    depends_on:
      - auth-service
      - docs-service
    networks:
      - papairs-network
    command: npm run serve
    restart: unless-stopped

  # ============================================
  # AUTH SERVICE (Spring Boot)
  # ============================================
  auth-service:
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    container_name: papairs-auth-service
    ports:
      - "8081:8081"
    env_file:
      - ./backend/auth-service/.env
    environment:
      - SERVER_PORT=8081
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      - SESSION_DURATION_HOURS=48
    networks:
      - papairs-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/auth/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ============================================
  # DOCS SERVICE (Spring Boot)
  # ============================================
  docs-service:
    build:
      context: ./backend/docs-service
      dockerfile: Dockerfile
    container_name: papairs-docs-service
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    networks:
      - papairs-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/api/docs/health"]
      interval: 30s
      timeout: 10s
      retries: 3

# ============================================
# NETWORKS
# ============================================
networks:
  papairs-network:
    driver: bridge
